# Generated by Django 4.2 on 2023-04-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phoneNumber',
            new_name='contact',
        ),
    ]
