# Generated by Django 4.2 on 2023-04-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_phonenumber_contact_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='phone',
        ),
    ]
